swagger: "2.0"
info:
  version: "1.0.0"
  title: Transaction Management API

# Définition des chemins (endpoints) pour les transactions
paths:
  /transactions:
    # Opération GET pour récupérer toutes les transactions du mois en cours
    get:
      summary: Get all transactions for the current month
      security:
        - BearerAuth: []  # Sécurité requise pour cette opération
      description: Returns a list of all transactions made by the user for the current month.
      responses:
        200:
          description: Success - Retrieved list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbidden
        500:
          description: Internal Server Error
          
  # Opération POST pour ajouter une nouvelle transaction
  # Chemin pour accéder à une transaction spécifique en utilisant son ID
  /transaction/{transactionId}:
    # Opération GET pour récupérer les détails d'une transaction spécifique
    get:
      summary: Get details of a transaction
      security:
        - BearerAuth: []  # Sécurité requise pour cette opération
      description: Returns the details of a specific transaction identified by {transactionId}.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve details
          required: true
          type: string
      responses:
        200:
          description: Success - Retrieved transaction details
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbidden
        404:
          description: Transaction not found - Invalid transaction ID
        500:
          description: Internal Server Error
    post:
      summary: Add a new transaction
      security:
        - BearerAuth: []  # Sécurité requise pour cette opération
      description: Adds a new transaction to the user's transaction list.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve details
          required: true
          type: string
        - name: transaction
          in: body
          description: Object representing the new transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        200:
          description: Success - Transaction successfully added
        400:
          description: Bad Request - Data validation error
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbidden
        500:
          description: Internal Server Error
    # Opération PUT pour mettre à jour les informations d'une transaction spécifique
    put:
      summary: Update information of a transaction
      security:
        - BearerAuth: []  # Sécurité requise pour cette opération
      description: Updates the information of a specific transaction identified by {transactionId}.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - name: transaction
          in: body
          description: Object representing the new transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      responses:
        200:
          description: Success - Transaction successfully updated
        400:
          description: Bad Request - Data validation error
        401:
          description: Unauthorized - Invalid token
        403:
          description: Forbidden
        404:
          description: Transaction not found - Invalid transaction ID
        500:
          description: Internal Server Error

# Définition des schémas de sécurité pour l'authentification
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header

# Définition des modèles de données pour les transactions
definitions:
  # Modèle de données pour mettre à jour une transaction
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Additional note for the transaction
  # Modèle de données pour une transaction
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        format: date-time
        description: Transaction date
      amount:
        type: number
        description: Transaction amount
      description:
        type: string
        description: Description
      balance:
        type: number
        description: Balance after the transaction
      transactionType:
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Additional note for the transaction